<?php

namespace Ifresco\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlfrescoAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlfrescoAccountRepository extends EntityRepository
{
}
