<?php

namespace Ifresco\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlfrescoFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlfrescoFavoriteRepository extends EntityRepository
{
}
