<?php

namespace Ifresco\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AllowedAspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowedAspectRepository extends EntityRepository
{
}
