<?php

namespace Ifresco\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchTemplateRepository extends EntityRepository
{
}
