<?php

namespace Ifresco\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchColumnSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchColumnSetRepository extends EntityRepository
{
	public function findAllVisible()
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT c FROM IfrescoClientBundle:SearchColumnSet c
				WHERE c.hideInMenu = false'
		);
	
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
